name: Bug Report
description: Report something that's not working correctly
labels: ["kind/bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please fill the form below.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Provide a general description of the issue, including what you're trying to accomplish. Add any relevant logs and configuration files.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: reproducible
    attributes:
      label: Steps to reproduce
      description: |
        Provide a link to a live example or a clear set of steps to reproduce this bug.
        Include any relevant code or configuration used.
    validations:
      required: true
  - type: textarea
    id: versions
    attributes:
      label: Versions in use
      description: Provide the relevant version information for this Chart, Cert Manager and your Kubernetes version.
    validations:
      required: true
  - type: textarea
    id: ctx
    attributes:
      label: Additional context
      description: Anything else you would like to add?
    validations:
      required: false
  - type: textarea
    id: voting
    attributes:
      label: Contributing
      value: |
        Vote on this issue by adding a 👍 reaction.
        To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).
